# Generated by Django 5.2.9 on 2025-12-03 09:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('page_name', models.CharField(max_length=200)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(default='pa11y', max_length=20)),
                ('issues_found', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='WCAGIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('wcag', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('selector', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('impact', models.CharField(blank=True, max_length=20)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcag_issues', to='audit.auditrecord')),
            ],
        ),
    ]
